version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" 
    restart: always 

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis-data:/data
      - redis-data:/var/lib/redis

  user-auth-server:
    build: .
    container_name: user-auth-mics-docker-app
    ports:
      - "3000:3000"
    environment:
      - DB_URL=${DB_URL}
      - REDIS_DB_URL=${REDIS_DB_URL}
      - sso_consumer=${sso_consumer}
      - local_consumer=${local_consumer}
      - singleSignOn_consumer=${singleSignOn_consumer}
      - Anish_Devfolio=${Anish_Devfolio}
      - Google_Page=${Google_Page}
      - Google_Client_ID=${Google_Client_ID}
      - Google_Client_Secret=${Google_Client_Secret}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

    depends_on:
      - mongodb
      - redis-stack

volumes:
  mongo-data: 
  redis-data:
