version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" 
    restart: always 

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: always 

  user-auth-server:
    build: .  # Assumes you have a Dockerfile in your Node.js app directory
    container_name: user-auth-mics-docker-app
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongodb:27017/UserAuthMicroservice
      - REDIS_DB_URL=redis://redis-stack:6379
    depends_on:
      - mongodb
      - redis-stack

volumes:
  mongo-data: 
  redis-data:
