name: Deploy Dist
on: [push, workflow_dispatch]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Code On Github Ubuntu VM
              uses: actions/checkout@v4
            #   run: |
            #     echo "Cloning Repo..."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git